name = "portfolio"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]
main = "./.output/server/index.mjs"

[assets]
directory = "./.output/public/"
binding = "STATIC_ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "32714eb4-5e83-41a7-af1d-5f2a035d1cbc"
migrations_dir = "drizzle"

[[d1_databases]]
binding = "CONTENT_DB"
database_name = "portfolio-content"
database_id = "aeb4dbaf-12e5-4698-a2a4-7e5b6b0b9a83"